version: '3'
services:
  ssl-router:
    image: joris/ssl-router:v1-latest
    build: ./
    hostname: ssl-router
    container_name: ssl-router
    volumes:
      - letsencrypt-data:/etc/letsencrypt
    environment:
      - EMAIL=joris.coppieters@gmail.com
      - DOMAIN=test.code-transform.com
      - INTERNAL_DOMAIN=site
      - INTERNAL_PORT=80
      - HTTP_PORT=8080
      - HTTPS_PORT=8090
      - CERT_GENERATOR=certbot
    ports:
      - "8080:80"
      - "8090:443"

  site:
    image: library/httpd:2.4
    hostname: site
    container_name: site
    ports:
      - "8070:80"

volumes:
  letsencrypt-data:
